apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nodes-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodes
  minReplicas: 1
  maxReplicas: 10 # Scale up to 10 nodes
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Value
          averageUtilization: 20 # Scale when CPU > 60%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30  # Prevent too rapid scaling up
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleDown:
      selectPolicy: Disabled
